// Code generated by "stringer -type=DispatcherStatus -trimprefix=DispatcherStatus -output dispatcher_status_string.go"; DO NOT EDIT.

package workers

import "strconv"

const _DispatcherStatus_name = "WaitProcessCancel"

var _DispatcherStatus_index = [...]uint8{0, 4, 11, 17}

func (i DispatcherStatus) String() string {
	if i < 0 || i >= DispatcherStatus(len(_DispatcherStatus_index)-1) {
		return "DispatcherStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DispatcherStatus_name[_DispatcherStatus_index[i]:_DispatcherStatus_index[i+1]]
}
