// Code generated by "stringer -type=TaskStatus -trimprefix=TaskStatus -output task_status_string.go"; DO NOT EDIT.

package workers

import "strconv"

const _TaskStatus_name = "WaitProcessSuccessFailRepeatWaitCancel"

var _TaskStatus_index = [...]uint8{0, 4, 11, 18, 22, 32, 38}

func (i TaskStatus) String() string {
	if i < 0 || i >= TaskStatus(len(_TaskStatus_index)-1) {
		return "TaskStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskStatus_name[_TaskStatus_index[i]:_TaskStatus_index[i+1]]
}
